### PR TITLE
Don't needlessly recompile

### PR DESCRIPTION
**Pull request by jorenvo**
skeptic causes cargo to monitor README.md.skt.md. This file does not
exist, nor is it created by any build script. Because of this cargo
will always rebuild even if nothing has changed:

$ RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info cargo build
... stale: /home/.../ply-rs-0.1.1/README.md.skt.md -- missing
... fingerprint error for ply-rs v0.1.1: mtime based components have changed
...
$ RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info cargo build
... stale: /home/.../ply-rs-0.1.1/README.md.skt.md -- missing
... fingerprint error for ply-rs v0.1.1: mtime based components have changed
etc.

Inspired by:
https://github.com/killercup/assert_cli/commit/ccc8af5561bc1ad5fa8f21cad82961c5a8f111d7

More info:
https://github.com/budziq/rust-skeptic/issues/25
https://github.com/rust-lang/cargo/issues/4213

### CODE REVIEW

**Comment by abusch** [comment]
This is a bug in skeptic that has been fixed in master but they haven't released a new version yet... As a workaround I've patched my Cargo.toml file to override skeptic's version...

**Comment by jorenvo** [comment]
Ok I see, you can just add in your own project's toml:

```toml
[dependencies]
skeptic = { git = "https://github.com/budziq/rust-skeptic" }
ply-rs = "0.1.1"
```
and then Cargo will use that to fulfill the dependency of ply-rs. I'm fairly new to Rust so I didn't know you could do that. Thanks!

I guess as long as this issue exists in the latest skeptic release I will keep this open since the above is not an ideal fix either.

**Comment by abusch** [comment]
You can also add the following, in case you don't want to add an explicit dependency on skeptic:

```
[patch.crates-io]
skeptic = { git = "https://github.com/budziq/rust-skeptic"}
```

But yeah, I agree, this is just a workaround until a new version of skeptic is released.

**Comment by jorenvo** [comment]
Even better, thanks again!

**Comment by Fluci** [comment]
Updated dependencies, seems to work now.

**Pull request closed without merging**
